### ISSUE TITLE
fabric + ssh forwarding + github

### ISSUE THREAD

**Issue by arneb** [DUGHH/meetings#3]
Ich könnte beim nächsten Treffen kurz erklären, wie ich mit Fabric und SSH-Forwarding im Deployment-Prozess für die Kommunikation mit GitHub die lokale (Entwickler-) Identität benutzte statt spezielle Deployment-Keys für die Server einzurichten.

**Comment by a7p** [comment]
dafür!

**Comment by WolfgangBoremski** [comment]
http://files.arnebrodowski.de/talks/dughh_fabric-github_20131113.pdf

**Comment by a7p** [comment]
man muss ssh-agent benutzen, wird in der troubleshooting section auf den der in den Folien verlinkten Github-Seite erwähnt und ist allen tugendhaften ssh-Nutzern wahrscheinlich nie aufgefallen.
